id: IAECA4B32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:47:47+00:00'
last_modified: '2022-06-08T01:22:20.075443+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21016
  title: པདྨ་ཕན་བདེ་ཆོས་གླིང་གསར་བཞེངས་ཀྱི་གཏམ་མུ་ཏིག་གསར་པའི་འཁྲི་ཤིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    9AAB:
      image_group_id: I1KG21161
      title: ''
      total_pages: 334
      order: 1
      base_file: 9AAB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
