id: P004478
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21016
  title: པདྨ་ཕན་བདེ་ཆོས་གླིང་གསར་བཞེངས་ཀྱི་གཏམ་མུ་ཏིག་གསར་པའི་འཁྲི་ཤིང་།
  author: ''
  volumes:
    a1c17894a75242ae9261eae1714a82c6:
      image_group_id: I1KG21161
      title: ''
      volume_number: 1
      total_pages: 334
